### ISSUE TITLE
deband_detail_mask throws TypeError

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/vs-deband#57]
```py
2022-12-29 01:27:21.841: root: ERROR: Traceback (most recent call last):
  File "C:\Users\light\AppData\Local\Programs\Python\Python310\lib\site-packages\vsengine\vpy.py", line 219, in _execute
    runpy.run_path(str(script), module.__dict__, module.__name__)
  File "C:\Users\light\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\light\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\light\AppData\Local\Programs\Python\Python310\lib\site-packages\vspreview\core\vsenv.py", line 19, in _monkey_runpy_func
    glob_dict = orig_runpy_run_code(*args, **kwargs)
  File "C:\Users\light\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Anime\Fansubbing\Git Repositories\Encoding Projects\[Kaleido-subs]\Work in Progress\Mahou Shoujo Madoka Magica [BD]_hidden\MegucaBD_NCOP1v1.py", line 79, in <module>
    FILTERED = filterchain(SRC.clip_cut)
  File "E:\Anime\Fansubbing\Git Repositories\Encoding Projects\[Kaleido-subs]\Work in Progress\Mahou Shoujo Madoka Magica [BD]_hidden\MegucaBD_NCOP1v1.py", line 39, in filterchain
    filtered = chain.filterchain(
  File "E:\Anime\Fansubbing\Git Repositories\Encoding Projects\[Kaleido-subs]\Work in Progress\Mahou Shoujo Madoka Magica [BD]_hidden\project_module\chain.py", line 98, in filterchain
    detail_mask = deband_detail_mask(boost, brz=(1250, 2500), rxsigma=[100, 300, 450])
  File "C:\Users\light\AppData\Local\Programs\Python\Python310\lib\site-packages\vsdeband\mask.py", line 27, in deband_detail_mask
    blur_ret_brz = Morpho.closing(blur_ret_brz.std.Binarize(brz[0]), coordinates=8)
  File "C:\Users\light\AppData\Local\Programs\Python\Python310\lib\site-packages\vstools\types\utils.py", line 113, in _wrapper
    return self.function(obj, *args, **kwargs)
  File "C:\Users\light\AppData\Local\Programs\Python\Python310\lib\site-packages\vsmasktools\morpho.py", line 278, in closing
    dilated = self.dilation(src, *args, func=func, **kwargs)
  File "C:\Users\light\AppData\Local\Programs\Python\Python310\lib\site-packages\vstools\types\utils.py", line 113, in _wrapper
    return self.function(obj, *args, **kwargs)
  File "C:\Users\light\AppData\Local\Programs\Python\Python310\lib\site-packages\vsmasktools\morpho.py", line 256, in dilation
    return self._mm_func(*args, func=func or self.dilation, mm_func=core.std.Maximum, op=ExprOp.MAX, **kwargs)
TypeError: Morpho._mm_func() missing 5 required positional arguments: 'radius', 'planes', 'thr', 'coords', and 'multiply'
```

unit tests when?

**Comment by Setsugennoao** [comment]
Fixed in https://github.com/Irrational-Encoding-Wizardry/vs-masktools/commit/6de4326a37fd75a7a29cb54d221dcf2283205ad1
